### PR TITLE
compile to C++

### PR DESCRIPTION
**Pull request by pardubice**
Thank you for your hard wokr. Please, can you compile this to C++ for Win?

### CODE REVIEW

**Comment by DetrikSyS** [comment]
As you can see the branch is testing, i won't make the pull request until is fully tested, besides that i'm setting my dev env for windows to compile it and test it.Greetings!

**Comment by pardubice** [comment]
Ok, ty

**Comment by DetrikSyS** [comment]
Can you cancel the pull request? :P

**Comment by pardubice** [comment]
How? :/

**Comment by kakaroto** [comment]
I've canceled the pull request.
@DetrikSys, can you recommit your changes and make sure to keep the same code formatting (same indentation, no tabs, etc..) otherwise it's impossible to review the changes.
Thanks for your work!

**Comment by DetrikSyS** [comment]
yea, sorry i was just using another IDE. i'll make the pull request as soon as the thing is totally fixed...i'll fix the indentation in the next commit.

**Pull request closed without merging**
