### PR TITLE
Fix an assumed typo and clean up the repo

### PR DESCRIPTION
**Pull request by vgturtle127**
I hope this is OK, but I went ahead and assumed that you wanted the
whole project to be GPLv3 and changed it. I also deleted all the empty
files.

I went ahead and added a simple .gitattributes and added a few entries
into the .gitignore file for Mac and Windows users ( I personally am
using a Cygwin setup for quick testing). If you have any concerns or
questions let me know. Hope this helps. :smile:

### CODE REVIEW

**Comment by kakaroto** [comment]
Hey, thanks! I just saw this because apparently gmail was blocking all mails from github! :(
Anyways, it's all good, yes, license should be GPL, but those empty files need to stay as they are needed for the autogen (otherwise it complains that they aren't there or it creates them), so they should stay there even though they are empty (you could always fill them out! haha)

**Comment by vgturtle127** [comment]
I had forgotten all about this. :laughing: 

I make pull requests all the time for projects, but unfortunately due to the nature of some projects (ambitious, niche, etc.), my PR's often go unnoticed.

I will update this PR as soon as I get home tonight, and I will probably update them to match more up to date GitHub standards as well.

I will also fill out all the empty files with as much information as possible. :smile:

**Comment by vgturtle127** [comment]
Just so you know, I am working on the project as we speak. It's taking a little longer since I am re-writing my own .gitignore file and having to fix some bugs in my Markdown editor. :blush:

**Comment by kakaroto** [comment]
No problem, there is no hurry after all. And thanks for doing this stuff, appreciated! :)

**Comment by vgturtle127** [comment]
It *should* be completely fixed now. :smile:

**Comment by vgturtle127** [comment]
OK, NOW it should be fixed. :laughing:

**Comment by kakaroto** [comment]
Nice! Thanks!
I noticed though that you changed all the `/* comments */` into `// comments`. I'm not a fan, but it's not a big deal.

**Comment by vgturtle127** [comment]
Well, not all of them. Just single line comments. That way you don't have wasted lines. But actually, my editor did that. I have a script that runs on source files automatically and does that, since that is what I like on most of my projects. I can always change them back with another script if you like. :smile:

**Comment by kakaroto** [comment]
Not just single liners, see all the copyright headers and this : https://github.com/vgturtle127/ps3xport/commit/0f4b729d028e6342541d370b3ea47de59dfd91ff#diff-37b42cc662d7bdb8dc7405671af8ad59R82
And I figured it was done automatically :p

**Comment by vgturtle127** [comment]
Huh, I guess I need to check the script. :laughing: 

It usually just does single line comments. I wonder what kind of bug could cause it to do a 2 line comment? REALLY weird...

**Pull request merged**
